---
 - name: Provisionando uma instancia EC2
   hosts: localhost
   connection: local
   gather_facts: False

   vars:
     instance_type: t2.micro
     security_group: eap-sg
     image: ami-0c322300a1dd5dc79
     region: us-east-1
     keypair_name: ec2_key
     count: 1

   tasks:  
       
     - name: Criação do security group
       local_action:
         module: ec2_group
         name: "{{ security_group }}"
         description: Security group para novas instancias EC2
         region: "{{ region }}"
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
         rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0
                       
     - name: ssh keypair for ec2
       ec2_key:
         region: "{{ region }}"
         key_material: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKar4py83FbZ+5Qb7L5iKXq566kPgPaz5Gh/YiVweHce63GYeeo9ZhPbQpV/CbbvC8333WwGVBLHSq99LawsyhGGbgVeHEFQLR2b2yS9VCQOHp/35SYVOp+CoPuStbU7xq7kshOXgLUYxH9GyRb59mrKM94CCz83nMMl3WJjnPuKWCbh1o/7SX9a+Cgj53SbxFFaDz3xIJI4LofRhexdPgAIHrQy9tev2xkuYqxSpF2GG9lxxujC2/y+t4mknaiL2utozvgb7at2aSgwpLRAZWX3hIv+WZo/VOGbOOwO0ga6o5o0uYQUXuQbd1FjSZ6+MmdFQULxynoe5lepxcqtif root@ansible-tower
         name: "{{ keypair_name }}"
         state: present
     
     - name: Criação da instancia EC2
       ec2:
         key_name: "{{ keypair_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: yes
         region: "{{ region }}"
         count: "{{ count }}"
       register: ec2
     
     - name: Adicionar a nova instancia no hosts file
       add_host:
         name: "{{ item.public_ip }}"
         groups: eap-servers
       with_items: "{{ ec2.instances }}"
      
     - name: Adicionar tag na instancia
       ec2_tag:
         resource: "{{ item.id }}"
         region: "{{ region }}"
         state: "present"
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Type: eapserver

     - name: Esperando pelo SSH
       wait_for:
         host: "{{ item.public_ip }}"
         port: 22
         state: started
       with_items: "{{ ec2.instances }}"
