---
 - name: Excluindo uma instancia EC2
   hosts: localhost
   connection: local

   vars:
     region: us-east-1

   tasks:
     - name: Coletar fatos EC2
       ec2_instance_facts:
         region: "{{ region }}"
         filters: us-east-1
           "tag:Type": eapserver
       register: ec2
     - debug: var=ec2

     - name: Excluindo uma instancia EC2
       ec2:
         instance_ids: "{{ item.instance_id }}"
         state: absent
         region: "{{ region }}"
       with_items: "{{ ec2.instances }}"

     - name: Excluindo Security Group
       ec2_group:
         name: "{{ security_group }}"
         description: Deletando o Security Group
         region: "{{ region }}"
         state: absent
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
         rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0       
