---
 - name: Automação de rede AWS
   hosts: localhost
   connection: local
   gather_facts: false
   
   tasks:
   
   - name: Criando Target Group com instancias alvo
     elb_target_group:
       name: tg-webserver-dev-inbound
       region: us-east-1
       protocol: http
       port: 80
       vpc_id: vpc-e1ebae9b
       health_check_protocol: http
       health_check_path: /
       successful_response_codes: "200"
       targets:
         - Id: i-0df7272f32df2fd15
           Port: 80
         - Id: i-0886a28a3440d8b92
           Port: 80
       state: present
       wait_timeout: 200
       wait: True
     
   - name: Criando Load Balancer
     elb_network_lb:
       name: lb-webserver-prod-inbound
       region: us-east-1
       subnets:
         - subnet-81b5c9bf
       
       listeners:
         - protocol: http
           load_balancer_port: 80
           intance_port: 80
           DefaultActions:
             - Type: forward
               TargetGroupName: tg-webserver-dev-inbound
       state: present
