---
 - name: Excluindo uma instancia EC2
   hosts: localhost
   connection: local
   
   vars:
     instance_type: t2.micro
     security_group: apache-sg
     image: ami-0c322300a1dd5dc79
     region: us-east-1
     keypair_name: ec2_key
     count: 1
   
   tasks:
     - name: Coletar fatos EC2
       ec2_instance_facts:
         region: "{{ region }}"
         filters:
           "tag:Type": webserver
       register: ec2
     - debug: var=ec2
     - debug: var=item.instance_id
     
     - name: Excluindo uma instancia EC2
       ec2:
         instance_ids: "{{ item.instance_id }}"
         state: absent
         region: "{{ region }}"
       with_items: "{{ ec2.instances }}"
