---
 - name: Provisionando uma instancia EC2
   hosts: localhost
   connection: local
   gather_facts: False

   vars:
     instance_type: t2.medium
     security_group: eap-sg
     image: ami-0c322300a1dd5dc79
     region: us-east-1
     keypair: sshkeypair
     count: 1

   tasks:  
       
     - name: Criação do security group
       local_action:
         module: ec2_group
         name: "{{ security_group }}"
         description: Security group para novas instancias EC2
         region: "{{ region }}"
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip: 0.0.0.0/0
         rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0

     - name: Criação da instancia EC2
       ec2:
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: yes
         region: "{{ region }}"
         keypair: "{{ keypair }}"
         count: "{{ count }}"
       register: ec2
     
     - name: Adicionar a nova instancia no hosts file
       add_host:
         name: "{{ item.public_ip }}"
         groups: eap-servers
       with_items: "{{ ec2.instances }}"
      
     - name: Adicionar tag na instancia
       ec2_tag:
         resource: "{{ item.id }}"
         region: "{{ region }}"
         state: "present"
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Type: eapserver

     - name: Esperando pelo SSH
       wait_for:
         host: "{{ item.public_ip }}"
         port: 22
         state: started
       with_items: "{{ ec2.instances }}"
