---
 - name: Excluindo uma instancia EC2
   hosts: eap-servers
   connection: local

   vars:
     region: us-east-1
     security_group: eap-sg

   tasks:
     - name: Coletar fatos EC2
       ec2_instance_facts:
         region: "{{ region }}"
       register: ec2
     - debug: var=ec2
     
     - name: Excluindo uma instancia EC2
       ec2:
         instance_ids: "{{ hostvars[groups['eap-servers'][0]['instance_id'] }}"
         state: restarted
         region: "{{ region }}"
       with_items: "{{ ec2.instances }}"
