---
- name: Basic machine post configurations
  hosts: all
  become: yes
  gather_facts: no
  connection: local
  tasks:

  - name: Setting SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive
      
  - name: Upgrading all packages
    yum:
      name: '*'
      state: latest
