---
- name: Basic machine post configurations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:

  - name: Creating manutenção group
    group:
      name: suporte
      state: present

  - name: Adding user Manutenção
    user:
      name: Manutencao
      comment: Administrador
      group: suporte

  - name: Setting SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive
      
  - name: Upgrading all packages
    yum:
      name: '*'
      state: latest
