---
- name: Basic machine post configurations
  hosts: all
  tasks:

  - name: Creating manutenção group
    group:
      name: suporte
      state: present

  - name: Adding user Manutenção
    user:
      name: Manutencao
      comment: Administrador
      uid: 1040
      group: suporte

  - name: Setting SELinux in permissive mode
    selinux:
      policy: targeted
      state: permissive
