---
- name: Installing and configuring Zabbix Agent
  hosts: all
  become: true
  tasks:
  
 # - name: Installing Zabbix Repository
 #   yum_repository:
 #     name: zabbix.repo:
 #     description: Zabbix Repository
 #     baseurl: https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm
 
  - name: Installing Zabbix Repo
    yum:
      name: https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm
      
  - name: Installing Zabbix Agent
    yum:
      name: zabbix-agent
      state: latest
      
  - name: Start Zabbix Agent and make persistent
    service:
      name: zabbix-agent
      state: started
      enabled: yes
